# Generated by Django 4.0.5 on 2022-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('sci_name', models.CharField(default=None, max_length=100)),
                ('is_ancient', models.BooleanField(default=False)),
                ('description', models.TextField(default=None, max_length=1000)),
                ('fact', models.TextField(default=None, max_length=750)),
                ('an_group', models.CharField(default=None, max_length=50)),
                ('habitat', models.CharField(default=None, max_length=50)),
                ('con_status', models.PositiveIntegerField(default=None)),
                ('diet', models.CharField(default=None, max_length=50)),
                ('avg_weight', models.PositiveIntegerField(default=None)),
                ('long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('img_1', models.CharField(max_length=500)),
                ('img_2', models.CharField(max_length=500)),
            ],
        ),
    ]
