# Generated by Django 4.0.5 on 2022-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='admin_rating',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
