# Generated by Django 4.0.5 on 2022-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_admin_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='avg_weight',
            field=models.FloatField(default=None),
        ),
    ]
