# Generated by Django 4.0.5 on 2022-06-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_avg_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='lat',
        ),
    ]
