# Generated by Django 4.0.5 on 2022-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_lat_alter_animal_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='height',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='length',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='life_span',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
    ]
