# Generated by Django 4.0.5 on 2022-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_animal_height_alter_animal_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='length',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='life_span',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
