# Generated by Django 4.0.5 on 2022-06-10 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0010_alter_animal_admin_rating_alter_animal_img_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='favourited_by',
            field=models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
