# Generated by Django 4.0.5 on 2022-06-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_favourited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='favourited_by',
        ),
    ]
